[package]
name = "boulderd"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
jwalk = "0.8.1"
regex = "1.11.1"
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
